# Generated by Django 2.2.8 on 2020-01-08 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldManInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=30)),
                ('age', models.PositiveIntegerField(max_length=3)),
                ('medical_history', models.CharField(max_length=30)),
                ('allergy', models.CharField(max_length=30)),
                ('blood_type', models.CharField(max_length=10)),
                ('drugs', models.CharField(max_length=30)),
                ('treatment', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='QrCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrCodeId', models.CharField(max_length=50)),
                ('old_man_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.OldManInfo')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('phone_number', models.CharField(max_length=50)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
