# Generated by Django 2.2.8 on 2020-01-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldmaninfo',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
