# Generated by Django 2.2.8 on 2020-01-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='object_id',
            field=models.CharField(max_length=50),
        ),
    ]
